# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - name: Relatorio de Testes
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: DotNET Tests
        path: "**/test-results.trx"                            
        reporter: dotnet-trx
        fail-on-error: true

  cd:
    name: CD deploy dockerHub
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: login docker hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{DOCKERHUB_USERNAME}}
          password: ${{DOCKERHUB_PASSWORD}}
      
      - name: build and push
        uses: docker/build-push-action@v4.1.1
        with:
          push: true
          tags: ${{vars.DOCKERHUB_REPO}}
      
